# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef5a59fa2e51c5237401620b239af459eec1bacc3e0d5abba37bbe014704bf45f19e24cca74fa56e3ac78194c081dea61c437bb1baf81204d1a55c9551173478

test:
  secret_key_base: dc7175027ee9d8b2ea32b0508a1773822aae297d5e08bf0498d7672abd9a1e402f1d0168ea1cb4ebdfb79b092f7330faa0219341bec2735e58a6991b5498dcd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
